---
- hosts: all
  become: true
  tasks:
    # Ubuntu tasks (unchanged)
    - name: update repo index (Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install apache2 package (Ubuntu)
      ansible.builtin.apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install support for php (Ubuntu)
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    # Fedora tasks with DNF4 forced
    - name: update repo index (Fedora)
      ansible.builtin.dnf:
        update_cache: yes
      environment:
        DNF_USE_DNF4: "1"
        LIBDNF_USE_DNF4: "1"
      when: ansible_distribution == "Fedora"

    - name: install httpd package (Fedora)
      ansible.builtin.dnf:
        name: httpd
        state: latest
      environment:
        DNF_USE_DNF4: "1"
        LIBDNF_USE_DNF4: "1"
      when: ansible_distribution == "Fedora"

    - name: add php support for apache (Fedora)
      ansible.builtin.dnf:
        name: php
        state: latest
      environment:
        DNF_USE_DNF4: "1"
        LIBDNF_USE_DNF4: "1"
      when: ansible_distribution == "Fedora"
