---
- hosts: all
  become: true
  tasks:

  - name: update repo index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution =="Ubuntu"

  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install support for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Force DNF backend
    ansible.builtin.set_fact:
    ansible_pkg_mgr: dnf
    when: ansible_distribution == "Fedora"

  - name: update repo index
    ansible.builtin.dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install httpd package
    ansible.builtin.dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Fedora"

  - name: add php support for apache
    ansible.builtin.dnf:
      name: php
      state: latest
    when: ansible_distribution == "Fedora"